fix: Add some pro patches
deepin-community/mpv pull request #4
Opened 2024-07-11 08:34 UTC by pengfeixx

Add some pro patches

Log: Add some pro patches

2024-07-12 01:38 UTC, hudeng-go requested changes

2024-07-12 01:38 UTC, hudeng-go commented on debian/changelog
> +mpv (0.38.0.1+deepin1-1) unstable; urgency=medium
v23和v25新的版本规则： 后最直接+deepin1(n), 所以这个的版本应该为0.38.0-1deepin1

2024-07-12 01:57 UTC, pengfeixx commented on debian/changelog
> +mpv (0.38.0.1+deepin1-1) unstable; urgency=medium
> v23和v25新的版本规则： 后最直接+deepin1(n), 所以这个的版本应该为0.38.0-1deepin1

已修改

2024-07-12 02:04 UTC, hudeng-go commented
/lgtm
/integrate

2024-07-12 02:05 UTC, hudeng-go commented
/integrate

2024-07-12 02:06 UTC, hudeng-go commented
/help

2024-07-14 02:37 UTC, hudeng-go commented
/approve

2024-07-14 03:56 UTC, hudeng-go commented
/approve

2024-07-14 03:57 UTC, merged